title: Evan Warren | Industrial Engineering Portfolio
description: Industrial Engineering portfolio showcasing projects in Systems Logistics, Operations Research, and Demand Forecasting.
logo: /assets/images/snowboard_excel_model_screenshot.png
theme: jekyll-theme-minimal
