title: Evan Warren | Industrial Engineering Portfolio
description: Industrial Engineering portfolio showcasing projects in Systems Logistics, Operations Research, and Demand Forecasting.
theme: jekyll-theme-minimal
